services:
  postgres:
    image: postgres:16.8-alpine
    environment:
      POSTGRES_DB: wagering
      POSTGRES_USER: wager
      POSTGRES_PASSWORD: wager
    ports: ['5432:5432']
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U wager -d wagering']
      interval: 3s
      timeout: 3s
      retries: 20
  localstack:
    image: localstack/localstack:3.8.1
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: us-east-1
    ports: ['4566:4566']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/localstack:/etc/localstack/init/ready.d
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 5s
      timeout: 3s
      retries: 20
